weelow/weelow/urls.py
# Weelow copyright, all rights reserved

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse 
from django.views import generic
from weelowapp import views, views_login, views_features
from weelowapp.multiurl import multiurl
from weelowapp.sitemaps import StaticViewSitemap

#sitemaps
sitemaps = {
    #'todos': TodoSitemap()
    'static': StaticViewSitemap
}

handler400 = views_features.custom_400
handler403 = views_features.custom_403
handler404 = views_features.custom_404
handler500 = views_features.custom_500

urlpatterns = patterns('',

    # General
    url(r'^i/EQ3vj5aPnOw6MYDpZySKsw4PKioEqUVJ7JH6d7KMHSisEyJGwr/', include(admin.site.urls)),

    # Register
    url(r'^i/register/$', views_login.register,name='register'),

    # Index (all billboards)
    #multiurl(
    #url(r'^$',views_login.register,name='register'),
    url(r'^$',views.BillboardView.as_view(), name='billboards'),
    #),

        # Create a Billboard
#        url(r'^i/sendbillboard/$', views.SendBillboradView.as_view(), name='send-billboard'),

    # Inside Billboard
    # Order by Helium
    multiurl(
        url(r'^(?P<slug>[-\w]+)/$', views.IndexView.as_view(ordering='-helium'), name='index'),    
        url(r'^(?P<slug>[-\w]+)/$', views.UnknownIndexView.as_view(ordering='-helium'), name='index'),
        ),

    # Order by Popping time
    multiurl(
        url(r'^(?P<slug>[-\w]+)/now$', views.IndexView.as_view(ordering='pop_date'), name='index_now'),    
        url(r'^(?P<slug>[-\w]+)/now$', views.UnknownIndexView.as_view(ordering='pop_date'), name='index_now'),
        ),

        # Publish a post
        url(r'^(?P<slug>[-\w]+)/send/$', views.SendView.as_view(), name='post-send'),
      
    # Login
    url(r'^i/login/$',views_login.login,{'template_name': 'login/login.html'},name='login'),

        # Password reset
        url(r'^i/password_reset/$', views_login.password_reset, name='password_reset'),
        url(r'^i/password_reset/done/$', views_login.password_reset_done, name='password_reset_done'),
        url(r'^i/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views_login.password_reset_confirm,
            name='password_reset_confirm'),
        url(r'^reset/done/$', views_login.password_reset_complete,name='password_reset_complete'),
        url(r'^i/confirm/(?P<activation_key>\w+)/(?P<username>\w+)/', views_login.register_confirm,name='register_confirmation'),
    

    # Media and static files

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT, }),

    # Profile

    # Order by Popping time
    multiurl(
        url(r'^a/(?P<username>\w+)/$', login_required(views.ProfileView.as_view(ordering='pop_date')), name='profile'), 
        url(r'^a/(?P<username>\w+)/$', login_required(views.VisitorProfileView.as_view(ordering='pop_date')), name='profile'), 
    ),

    # Order by helium
#    multiurl(
#        url(r'^a/(?P<username>\w+)/now/$', login_required(views.ProfileView.as_view(ordering='-helium')), name='profile_now'), 
#        url(r'^a/(?P<username>\w+)/now/$', login_required(views.VisitorProfileView.as_view(ordering='-helium')), name='profile_now'), 
#    ),

        # Pick and Pop on ProfileView 
        url(r'^a/(?P<username>\w+)/create_date/$', login_required(views.Pick_Click), name='post-pick'),
        url(r'^a/(?P<username>\w+)/create_pop/$', login_required(views.Pop_Click), name='post-pop'),
        url(r'^a/(?P<username>\w+)/pop_without_helium/$', login_required(views.pop_without_helium), name='pop_without_helium'),

        # Pick and Pop on VisitorProfileView
        url(r'^a/(?P<username>\w+)/create_pick/$', views.Pick_Click, name='visitor-post-pick'), 
        url(r'^a/(?P<username>\w+)/create_pop/$', views.Pop_Click, name='visitor-post-pop'), 

        # Post on profile  
        url(r'^a/(?P<username>\w+)/send/$', views.SendView.as_view(), name='post-send-profile'),
        
        # logout  
        url(r'^a/(?P<username>\w+)/logout/$',views_login.logout_then_login,name='logout'),

        # Delete a Post
        url(r'^a/(?P<username>\w+)/(?P<pk>[\w]+)/delete/$', login_required(views.RequestDeleteView.as_view()),name='delete'),

        # Change avatar
        url(r'^a/(?P<username>\w+)/avatar/$', views_login.add, {'template_name': 'avatar_app/add.html'}, name='avatar_profile'),

    # Avatar app

    #url(r'^accounts/avatar/', include('avatar.urls')),

    # Google sitemaps

    url(r'^sitemap.xml$','django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps,}),
    url(r'^googlec6818a23b9beef1a\.html/$', lambda r: HttpResponse("google-site-verification: googlec6818a23b9beef1a.html", content_type="text/plain")),
    url(r'^robots.txt$', include('robots.urls')),
    
)

weelow/weelowapp/forms.py
# Weelow copyright, all rights reserved

from __future__ import unicode_literals

from collections import OrderedDict

from django import forms
from django.forms.utils import flatatt
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.html import format_html, format_html_join
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext, ugettext_lazy as _
from django.template.defaultfilters import slugify
import itertools

from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, identify_hasher
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.utils.safestring import mark_safe

from django import forms
from django.forms.models import ModelForm
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils.text import capfirst
from django.forms.extras.widgets import SelectDateWidget

from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.models import User 

from weelowapp.models import Post, Pick, Billboard
from weelowapp.fields import PrettyDateField

import datetime

class UserCreationForm(ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }

    username = forms.RegexField(
        max_length=30,
        regex=r'^[\w]+$',        
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "_ characters.")
                        },
        widget=forms.TextInput(attrs={'placeholder': 'Username'})
        )

    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
        )

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
        )

    class Meta:
        model = User
        fields = ("username","email")

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('That email is already taken')
    
    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username__iexact=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )
    """   
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2
    """


    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data['email']
        if commit:
            user.is_active = False
            user.save()
        return user

class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = forms.CharField(max_length=254,
        widget=forms.TextInput(attrs={'placeholder':'Email or username'}))

    password = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

    error_messages = {
        'invalid_login': _('Please enter a correct %(username)s and password. '
                           'Note that both fields may be case-sensitive.'),
        'inactive': _("Please validate your email!"),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

        # Set the label for the "username" field.
        UserModel = get_user_model()
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)
        
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            
            if self.user_cache is None:
                raise forms.ValidationError(
                    mark_safe(self.error_messages['invalid_login']),
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                    
                )

                          
                
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        
        
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )
    

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

class PasswordResetForm(forms.Form):
    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
        )

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail
        UserModel = get_user_model()
        email = self.cleaned_data["email"]
        active_users = UserModel._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)

            if html_email_template_name:
                html_email = loader.render_to_string(html_email_template_name, c)
            else:
                html_email = None
            send_mail(subject, email, from_email, [user.email], html_message=html_email)


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
        )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Password confirmation'})
        )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',

weelow/weelowapp/templates/login/base.html
<!--Weelow © copyright, all rights reserved-->

{% load admin_static %}{% load firstof from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<meta name="description" content="Weelow is a visual tool that allows artists to share their agenda" />
<title>{% block title %}Weleow - the agenda for artists{% endblock %}</title>
<meta charset="utf-8">

<!--Imported from main.html head-->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="{{ STATIC_URL }}logos/weecon.ico" />
<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
<link href="{{ STATIC_URL }}css/animation.css" rel="stylesheet">


<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/nav-menu-1.js"></script>


<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{{ STATIC_URL }}css/base.css{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
 <!-- Start Visual Website Optimizer Asynchronous Code -->
<script type='text/javascript'>
var _vwo_code=(function(){
var account_id=149288,
settings_tolerance=2000,
library_tolerance=2500,
use_existing_jquery=false,
// DO NOT EDIT BELOW THIS LINE
f=false,d=document;return{use_existing_jquery:function(){return use_existing_jquery;},library_tolerance:function(){return library_tolerance;},finish:function(){if(!f){f=true;var a=d.getElementById('_vis_opt_path_hides');if(a)a.parentNode.removeChild(a);}},finished:function(){return f;},load:function(a){var b=d.createElement('script');b.src=a;b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};d.getElementsByTagName('head')[0].appendChild(b);},init:function(){settings_timer=setTimeout('_vwo_code.finish()',settings_tolerance);this.load('//dev.visualwebsiteoptimizer.com/j.php?a='+account_id+'&u='+encodeURIComponent(d.URL)+'&r='+Math.random());var a=d.createElement('style'),b='body{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;}',h=d.getElementsByTagName('head')[0];a.setAttribute('id','_vis_opt_path_hides');a.setAttribute('type','text/css');if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(d.createTextNode(b));h.appendChild(a);return settings_timer;}};}());_vwo_settings_timer=_vwo_code.init();
</script>
<!-- End Visual Website Optimizer Asynchronous Code --> 
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">


<div class="video">
<div class="video-cover"></div>
<video  autoplay loop muted src="{{ MEDIA_URL }}video/ny.mp4" type="video/mp4" poster >    
</video>
<!--<img src="{{ MEDIA_URL }}video/stanford-bg.jpg">-->
</div>
<!--<div class="login-bg-box">
   <div class="login-bg-image"></div>
</div>
-->
<div class="about-link"> <a target="_blank" href="http://about.weelow.com">About Weelow</a></div>



<!-- Container -->
<div id="container">



<!--<a href = "http://about.weelow.com" data-toggle="modal" class="concept-info" ></a>-->

<a  href="{% url 'billboards' %}"><div class="logo-weelow active-loader"></div></a>
<div class="logo-title">the agenda for artists</div>

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
               <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> 
                {% endif %}
                <!--<a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>-->
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

weelow/weelowapp/templates/login/base_site.html
{% extends "login/base.html" %}

{% block title %}{{ title }}  {{ Weelow|default:_('Weelow') }}{% endblock %}

{% block branding %}
{#<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Weelow') }}</a></h1>#}
{% endblock %}

{% block nav-global %}{% endblock %}

weelow/weelowapp/templates/login/confirm.html
{% extends "login/login.html" %}
{% load i18n %}

{% block breadcrumbs %}
{% endblock %}

{% block title %}e-mail validated{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<div class="login-text-box">
<h1>{% trans "Your e-mail is validated, thank you!" %}</h1>
</div>
<div class="form-row">
<a href= "{% url 'billboards' %}"><input type="submit" value="{% trans 'GO AHEAD' %}"/></a>
</div>
{% endblock %}

weelow/weelowapp/templates/login/confirm_email.html
{% extends "login/login.html" %}
{% load i18n %}

{% block breadcrumbs %}
{% endblock %}

{% block title %}confirm e-mail{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}
<div class="login-text-box">

<h1>{% trans "Please confirm your email!" %}</h1>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
</div>


<div class="form-row">
{#<a href= "{% url 'billboards' %}"><input type="submit" value="{% trans 'GO AHEAD' %}"/></a>#}
</div>
{% endblock %}

weelow/weelowapp/templates/login/confirm_expired.html
{% extends "login/login.html" %}
{% load i18n %}

{% block breadcrumbs %}
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your link has expired, Please resend an e-mail." %}</p>

<p><a href= "{% url 'post:index' %}"><input type="submit" value="{% trans 'Go ahead' %}"/></a></p>

{% endblock %}

weelow/weelowapp/templates/login/login.html
{% extends "login/base_site.html" %}

{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/login.css" />{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}f

{% block nav-global %}{% endblock %}

<title>{% block title %}login on Weelow{% endblock %}</title>

{% block breadcrumbs %}{% endblock %}
{% block welcome-msg %}{% endblock %}
{% block userlinks %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
  {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">
<form action="{{ app_path }}" method="post" id="login-form" autocomplete="off">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    <!--<label for="id_username" class="required">{{ form.username.label }}:</label>--> {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    <!--<label for="id_password" class="required">{% trans 'Password:' %}</label>-->   {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}"  />
  </div>
  {% url 'admin_password_reset' as password_reset_url %}
  
  <div class="password-reset-link">
    <a href="{% url 'password_reset' %}">Forgotten your password or username?</a>
  </div>

   <div class="submit-row">
    <!-- <label>&nbsp;</label>--><input lass="active-loader" type="submit" value="ENTER WEELOW" />
   </div>

   <div class="submit-row">
    <input class="active-loader" type="button" value="REGISTER" onClick="javascript:location.href = '{% url 'register' %}';">
  </div>
  
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>



</div>

{% endblock %}

weelow/weelowapp/templates/login/password_change_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

weelow/weelowapp/templates/login/password_change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}<div id="content-main">

<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">{% trans 'Old password' %}:</label>{{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">{% trans 'New password' %}:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">{% trans 'Password (again)' %}:</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}